[buildPlans.aosevka]
family = "Aosevka"
design = [
  "sans",
  "sp-term",

  "calt-arrow", # => ->
  "calt-ineq", # >= <=
  "calt-eqeq", # == !=
  "calt-center-ops",
  "calt-exeq", # != !==
  "calt-exeq-alt-1", # !=
  "calt-brst", # (* *)
  "calt-plusplus", # +++++
  "calt-kern-dotty", # std::cout ::: :=
  "calt-llgg", # << >>
  "calt-llggeq", # >>= <<=
  "calt-dotoper", # ...
  "calt-html-comment", # <!---

  "v-a-doublestorey", # a
  "v-g-doublestorey", # g
  "v-m-earless-single-arch-shortleg", # m
  "v-n-earless-rounded-straight", #n
  "v-t-flat-hook", # t
  "v-u-without-bar", # u
  "v-y-cursive", # y
  "v-w-curly", # w
  "v-capital-q-crossing", # Q
  "v-three-flattop", # 3
  "v-four-open-non-crossing", # 4
  "v-six-closed-contour", # 6
  "v-underscore-above-baseline", # hello_world
  "v-ampersand-et", # true && true
  "v-percent-rings-connected", # %%%
]
italic = [
  "v-a-doublestorey-tailed", # a
  "v-h-tailed", # h
  "v-t-standard", # t
  "v-n-earless-rounded-tailed", # n
  "v-m-earless-single-arch-shortleg-tailed", # m
  "v-q-tailed", # q
]


[buildPlans.aosevka.weights.regular]
menu  = 400
shape = 425
css   = 425

[buildPlans.aosevka.weights.bold]
menu  = 700
shape = 700
css   = 700

[buildPlans.aosevka.slopes]
upright = "normal"
italic = "italic"

[buildPlans.aosevka.widths.normal]
shape = 576 # Unit Width, measured in 1/1000 em.
menu  = 5 # Width grade for the font's names.
css   = "expanded" # "font-stretch' property of webfont CSS.

[buildPlans.aosevka-compressed]
family = "Aosevka Compressed"
design = [
  "sans",
  "sp-term",

  "calt-arrow", # => ->
  "calt-ineq", # >= <=
  "calt-eqeq", # == !=
  "calt-center-ops",
  "calt-exeq", # != !==
  "calt-exeq-alt-1", # !=
  "calt-brst", # (* *)
  "calt-plusplus", # +++++
  "calt-kern-dotty", # std::cout ::: :=
  "calt-llgg", # << >>
  "calt-llggeq", # >>= <<=
  "calt-dotoper", # ...
  "calt-html-comment", # <!---

  "v-a-doublestorey", # a
  "v-g-doublestorey", # g
  "v-m-earless-single-arch-shortleg", # m
  "v-n-earless-rounded-straight", #n
  "v-t-flat-hook", # t
  "v-u-without-bar", # u
  "v-y-cursive", # y
  "v-w-curly", # w
  "v-capital-q-crossing", # Q
  "v-three-flattop", # 3
  "v-four-open-non-crossing", # 4
  "v-six-closed-contour", # 6
  "v-underscore-above-baseline", # hello_world
  "v-ampersand-et", # true && true
  "v-percent-rings-connected", # %%%
]
italic = [
  "v-a-doublestorey-tailed", # a
  "v-h-tailed", # h
  "v-t-standard", # t
  "v-n-earless-rounded-tailed", # n
  "v-m-earless-single-arch-shortleg-tailed", # m
  "v-q-tailed", # q
]

[buildPlans.aosevka-compressed.weights.regular]
menu  = 400
shape = 425
css   = 425

[buildPlans.aosevka-compressed.weights.bold]
menu  = 700
shape = 700
css   = 700

[buildPlans.aosevka-compressed.slopes]
upright = "normal"
italic = "italic"

[buildPlans.aosevka-compressed.widths.normal]
shape = 500 # Unit Width, measured in 1/1000 em.
menu  = 5 # Width grade for the font's names.
css   = "normal" # "font-stretch' property of webfont CSS.
